using CopilotScope.Collector.Domain;

namespace CopilotScope.Seeder;

/// <summary>
/// Hand-authored, coherent long conversations — real developers working a single problem end to
/// end across ~30 turns. Unlike the persona generator (statistically-shaped but content-random),
/// every prompt/response here is written to read like an actual session, so the dashboard's
/// transcript view shows a genuine chat rather than disconnected sample lines.
/// </summary>
public static class ScriptedSessionCatalog
{
    public static readonly ScriptedSession[] All =
    [
        RateLimiter,
        OtlpIncident,
        InfiniteScrollSearch,
    ];

    // ── Session 1 ─────────────────────────────────────────────────────────────────────────────
    // A backend dev builds a distributed token-bucket rate limiter in the auth-gateway, end to
    // end: design → Redis/Lua impl → fail-open → tests → a real race bug (unnormalized client id)
    // → load test → admin endpoints → ship. VS Code, so all editor signals are present.
    private static ScriptedSession RateLimiter => new(
        Slug: "auth-ratelimit",
        Repository: "https://github.com/acme/auth-gateway",
        Branch: "feature/rate-limiting",
        Emitter: EmitterKind.VSCode,
        DefaultModel: "claude-sonnet-5",
        EditsAccepted: 34, EditsRejected: 6, ThumbsUp: 4, ThumbsDown: 1,
        LinesAdded: 486, LinesRemoved: 118,
        Turns:
        [
            new("I need to add rate limiting to the auth-gateway. We're getting hammered on /token by a few misbehaving clients. What's the cleanest per-client approach?",
                "A token-bucket is the usual fit: each client gets a bucket that refills at a steady rate and each request costs one token. It smooths bursts better than a fixed window and is cheap. Since you run multiple gateway instances the bucket state has to live in Redis so the limit is shared, not per-process. Want me to sketch the interface first?"),
            new("Yeah, start with the interface.",
                "Added IRateLimiter in src/AuthGateway/RateLimiting/IRateLimiter.cs with a single Task<RateLimitResult> AcquireAsync(string clientId, CancellationToken ct). RateLimitResult carries Allowed, Remaining and RetryAfter so the middleware can set headers. Kept it async because the Redis round-trip is I/O.",
                Tools: ["createFile"]),
            new("Good. Now the Redis-backed implementation. Refill rate should be configurable per client tier.",
                "Implemented RedisTokenBucket. It stores two fields per client — tokens and lastRefill — and computes the refill lazily on each acquire: tokens = min(capacity, tokens + elapsed * refillPerSecond). Tier config (capacity + refill) comes from RateLimitOptions. I used a Lua script so the read-modify-write is atomic on the Redis side.",
                Tools: ["createFile", "editFile"]),
            new("Why the Lua script instead of MULTI/EXEC?",
                "MULTI/EXEC queues commands but can't branch on a value it just read. I need to read the current tokens, compute the refill, decide allow/deny, and write back atomically — a compare-and-set that depends on the read, which EXEC can't express. A Lua script runs server-side as one atomic unit and can do the conditional, in a single round-trip instead of a watch/retry loop."),
            new("Show me the Lua.",
                """
                Here it is — KEYS[1] is the bucket key, ARGV are now/capacity/refillRate/cost:
                ```lua
                local b = redis.call('HMGET', KEYS[1], 'tokens', 'ts')
                local tokens = tonumber(b[1]) or tonumber(ARGV[2])
                local ts = tonumber(b[2]) or tonumber(ARGV[1])
                local delta = math.max(0, tonumber(ARGV[1]) - ts)
                tokens = math.min(tonumber(ARGV[2]), tokens + delta * tonumber(ARGV[3]))
                local allowed = tokens >= tonumber(ARGV[4])
                if allowed then tokens = tokens - tonumber(ARGV[4]) end
                redis.call('HMSET', KEYS[1], 'tokens', tokens, 'ts', ARGV[1])
                redis.call('PEXPIRE', KEYS[1], 3600000)
                return { allowed and 1 or 0, tokens }
                ```
                """),
            new("The PEXPIRE — why an hour?",
                "It's just garbage collection for idle clients: a client that stops calling would otherwise leave its bucket key in Redis forever. An hour is comfortably longer than any refill window, so an active client's key is always refreshed before it expires and an inactive one gets cleaned up. Nothing depends on the exact value."),
            new("OK. Now wire it into the middleware.",
                "Added RateLimitMiddleware. It pulls the client id from the validated client_id claim, calls AcquireAsync, and on denial short-circuits with 429 plus Retry-After and X-RateLimit-Remaining headers. On allow it sets X-RateLimit-Remaining and continues the pipeline.",
                Tools: ["editFile"]),
            new("What happens if Redis is down? I don't want the whole gateway to hard-fail on a rate-limit check.",
                "Good call — right now an exception would surface as a 500. I'll make it fail-open: wrap the acquire in try/catch, and if Redis is unreachable log a warning and allow the request. Rate limiting is a protection, not a correctness invariant — better to serve traffic unthrottled for a few seconds than to take the gateway down with Redis.",
                Tools: ["editFile"]),
            new("Agreed, fail-open. But add a metric so we can see when we're in that degraded state.",
                "Added ratelimit_failopen_total incremented in the catch block, and ratelimit_decision_total{decision=allow|deny} on the happy path, both tagged by tier. A spike in fail-open is now visible on the dashboard even though requests still flow.",
                Tools: ["editFile"]),
            new("Now tests. Start with the refill math — that's where bugs hide.",
                "Added RedisTokenBucketTests using a fake clock. Cases: full bucket allows immediately; empty bucket denies; after exactly 1/refillRate seconds one token is available again; refill never exceeds capacity even after a long idle. All green.",
                Tools: ["createFile", "runTests"]),
            new("Add one for the burst case — capacity 10, fire 15 in a tight loop, expect 10 allow then 5 deny.",
                "Added it. The first 10 acquires return Allowed=true, the next 5 return Allowed=false with RetryAfter > 0. Passing.",
                Tools: ["editFile", "runTests"]),
            new("Hmm, that RetryAfter — is it accurate or a fixed guess?",
                "It's computed as (cost - tokens) / refillRate — how long until enough tokens accrue for this request — so it's accurate to the model, not a fixed guess. I round up to whole seconds because Retry-After is expressed in seconds."),
            new("Wait, rounding up on a sub-second refill means a client could retry too early and still get denied. Problem?",
                "Rounding up is the safe direction: the client waits at least long enough, never too little, so it won't retry early — if anything it waits a hair longer than strictly necessary. Rounding down would cause exactly the early-retry-still-denied loop you're worried about. Current behavior is correct; I'll add a comment saying so.",
                Tools: ["editFile"]),
            new("Good. Run the whole suite.",
                "Ran it — 41 passed, 0 failed. The rate-limiting namespace accounts for 12 of those.",
                Tools: ["runTests"]),
            new("Let me load-test it. Write a small k6 script hitting /token at 500 rps across 50 client ids.",
                "Added loadtest/token-ratelimit.js: 50 VUs each pinned to a client id, constant-arrival-rate at 500 rps for 2 minutes. It asserts 429s only appear for clients over their tier and that p95 added latency from the limiter stays under 5 ms.",
                Tools: ["createFile"]),
            // The debugging stretch — switch to the heavier model, and a couple of slow responses.
            new("Ran it. p95 limiter latency is 1.8 ms, nice. But I'm seeing a few 429s for clients that shouldn't be over. Race condition?",
                "The Lua itself is atomic, so a single-node race is unlikely. But if Redis is clustered and the bucket keys hash to unexpected slots, or you're reading a replica, you'd see stale tokens. Can you confirm the load test points at the primary and whether cluster mode is on?",
                Model: "claude-opus-4-8", TtftMs: 4200),
            new("It's a single primary, cluster off. So not that.",
                "Then let's look at the client-id extraction. If two concurrent requests from the same client momentarily resolve to different ids — the claim trimmed or cased inconsistently — they'd hit different buckets and the accounting would drift. Let me check how we derive the key.",
                Tools: ["readFile", "grepSearch"]),
            new("Find it?",
                "Found it. The key is built as ratelimit:{client_id} but client_id isn't normalized — some tokens carry it as a GUID with braces, some without. So {abc} and abc are two buckets for the same client, each with full capacity. Under load that doubles the effective limit and produces the odd early-429 when requests split across the two. I'll normalize: strip braces and lowercase before building the key.",
                Tools: ["editFile"]),
            new("Nice catch. Add a test that locks that in.",
                "Added KeyNormalization_TreatsBraceAndCaseVariantsAsSameClient: acquires against {ABC} and abc and asserts they share one bucket — the 11th request across the two variants is denied at capacity 10. Passing.",
                Tools: ["editFile", "runTests"]),
            new("I want the limits reloadable without a redeploy.",
                "Wired RateLimitOptions through IOptionsMonitor, so editing the tier config triggers OnChange and subsequent acquires use the new capacity/refill immediately. Existing balances aren't reset — they just refill toward the new capacity — which is the least surprising behavior.",
                Model: "claude-sonnet-5", Tools: ["editFile"]),
            new("What if someone sets refillRate to 0 by mistake?",
                "With refillRate 0 a bucket never refills, so a client is permanently blocked once drained — a config footgun. I added RateLimitOptions.Validate() to reject non-positive refill rates and capacities at startup and log the offending tier. On a hot-reload with a bad value I keep the last-known-good config and log an error rather than applying it.",
                Tools: ["editFile"]),
            new("Now the admin side — I want an endpoint to inspect a client's current bucket.",
                "Added GET /admin/ratelimit/{clientId} returning current tokens, capacity, refill rate and computed time-to-full, behind the existing admin auth policy. It's read-only — it computes the lazy refill for display but doesn't consume a token.",
                Tools: ["createFile", "editFile"]),
            new("Can I also reset a bucket from there? Support sometimes needs to unblock someone.",
                "Added DELETE /admin/ratelimit/{clientId} which deletes the bucket key so the next request starts full. Logged with the admin's identity for audit. I kept it a separate verb so read access and reset access can be authorized differently later.",
                Tools: ["editFile"]),
            new("Document the tiers and the headers in the README.",
                "Added a Rate limiting section to src/AuthGateway/README.md: the three tiers with capacity/refill, the X-RateLimit-Remaining / Retry-After / 429 contract, the fail-open behavior, the two admin endpoints, and the metric names for dashboards.",
                Tools: ["editFile"]),
            new("One more: the 429 body is empty — return a small JSON with the retry hint.",
                """The deny path now writes {"error":"rate_limited","retryAfterSeconds":N} with content-type application/json, matching the Retry-After header. The header stays authoritative; the body is a convenience for clients that don't read headers.""",
                Tools: ["editFile"]),
            new("Does that break the existing 429 test that asserted an empty body?",
                "It would have — I updated Returns429WhenOverLimit to assert the JSON shape and that retryAfterSeconds equals the header. Re-ran the file: 12 passed.",
                Tools: ["editFile", "runTests"]),
            new("Let me eyeball the middleware header logic — show me the final InvokeAsync.",
                "Here's RateLimitMiddleware.InvokeAsync — it sets X-RateLimit-Remaining on both paths, adds Retry-After only on deny, and the fail-open catch allows through without headers. The client-id normalization now happens once at the top and is reused for both the key and the metric tag.",
                Tools: ["readFile"]),
            new("The remaining header is a double — should be an int. Clients choke on '7.0'.",
                "Fixed — I floor it to an int before writing, since a partial token isn't spendable anyway. X-RateLimit-Remaining now emits 7, not 7.0.",
                Tools: ["editFile"]),
            new("Do we test that the fail-open metric increments?",
                "We didn't. Added FailOpen_IncrementsCounter_AndAllows using a Redis stub that throws: asserts the request is allowed and ratelimit_failopen_total went up by one. Passing.",
                Tools: ["editFile", "runTests"]),
            new("Ship it. Write the commit message.",
                "Staged. Suggested message: feat(auth-gateway): per-client token-bucket rate limiting — body summarizing the Redis Lua bucket, fail-open with metrics, hot-reloadable tiers, admin inspect/reset endpoints and the 429 contract. Want me to open the PR?"),
            new("Open it against develop, and add the load-test numbers to the description.",
                "Opened PR #212 into develop. Description includes the p95 limiter latency (1.8 ms), the 500 rps / 50-client setup, the tier table, and a note on the key-normalization fix that resolved the spurious 429s. CI is running.",
                Tools: ["runCommand"]),
            new("Thanks, that was a good session.",
                "Anytime — nicely scoped work. If you want a follow-up, a sliding-window option for endpoints where a hard ceiling matters more than burst allowance is the natural next step, but the token bucket covers the /token abuse case well. Good to ship."),
        ]);

    // ── Session 2 ─────────────────────────────────────────────────────────────────────────────
    // On-call incident: the collector silently drops OTLP batches after a deploy. A real debugging
    // arc with a wrong first hypothesis, genuine frustration, a rollback, the actual root cause
    // (middleware consuming the request body before the streaming decoder), tests, and a
    // postmortem. Claude Code CLI, so no editor signals — the CLI story on the dashboard.
    private static ScriptedSession OtlpIncident => new(
        Slug: "otlp-incident",
        Repository: "https://github.com/acme/data-pipeline",
        Branch: "hotfix/otlp-drop",
        Emitter: EmitterKind.ClaudeCode,
        DefaultModel: "claude-opus-4-8",
        EditsAccepted: 0, EditsRejected: 0, ThumbsUp: 0, ThumbsDown: 0,
        LinesAdded: 0, LinesRemoved: 0,
        Turns:
        [
            new("Prod alert: the collector is dropping ~30% of OTLP batches since the 14:00 deploy. Ingest fell off a cliff. Where do I even start?",
                "Separate 'dropped at the edge' from 'accepted but not stored' first. Two quick checks: the HTTP status distribution on /v1/traces (4xx/5xx vs 200-but-empty), and the decode error logs. If we return 200 and lose data after, it's decode/parse; if we return errors, it's transport. Can you pull the last 10 minutes of status codes?"),
            new("Mostly 200s. A handful of 400s but nothing like 30%.",
                "So we're accepting the requests and losing the data downstream — decode or aggregation. Let me look at the decoder path. What changed in the 14:00 deploy? A PR number would narrow it fast.",
                Tools: ["runCommand"]),
            new("PR #204, 'switch OTLP ingestion to streaming decode'.",
                "That's almost certainly it. Streaming decode reads the request body once as a stream; if anything upstream already consumed or transformed the body, the stream is empty or misaligned by the time protobuf reads it. Let me look at the new decode entrypoint.",
                Tools: ["readFile"]),
            new("Go.",
                "Looking at OtlpDecoder.DecodeAsync — it reads request.Body straight into the protobuf reader, and there's no content-encoding handling here anymore; the old code had a gzip branch. If clients send Content-Encoding: gzip (the OTLP exporters do by default) we're feeding gzip bytes into protobuf, which fails to parse and yields an empty batch — dropping exactly the gzipped share.",
                Tools: ["grepSearch"]),
            new("That fits — the SDKs gzip by default. So we just re-add the gzip branch?",
                "That's the fix in spirit. I'll wrap the body in a GZipStream when Content-Encoding: gzip is present before handing it to the decoder. Let me add it back.",
                Tools: ["editFile"]),
            new("Deploy that to staging and replay the captured traffic.",
                "Added the branch and pushed to staging. Replaying the captured 14:05 batch now.",
                Tools: ["editFile", "runCommand"]),
            new("Still dropping. Same rate.",
                "Then let me confirm the branch is actually hit — maybe the header check is wrong-cased or the value carries parameters. Adding a debug log of Content-Encoding as received.",
                Tools: ["editFile", "runCommand"], ToolErrorIndexes: [1]),
            new("Log says 'gzip'. So the branch should fire.",
                "So the branch fires but decode still fails — meaning gzip isn't the whole story, or my wrapping is wrong. Let me decode one captured body by hand in a scratch test and see exactly where it breaks.",
                Tools: ["createFile", "runTests"], ChatError: true, ErrorType: "NetworkTimeout", TtftMs: 3600),
            new("This still doesn't work. We're bleeding data in prod — can we just roll back #204 while we debug?",
                "Yes — roll back now, debug after. Reverting to the pre-14:00 image restores the known-good buffered decode and stops the drop immediately. I'll keep the staging box on the new build to find the real cause. Rolling back prod.",
                Tools: ["runCommand"], TtftMs: 4800),
            new("Rolled back, ingest recovered. Now let's actually find it. You said your wrapping might be wrong.",
                "Right. In the scratch test I gunzip the captured body and protobuf-parse it — that succeeds, so the payload is fine and gzip is genuinely the encoding. Which means in the request path something reads the body before my gzip branch. Let me trace the middleware order.",
                Tools: ["readFile", "grepSearch"]),
            new("Middleware order — what's in front of the decoder?",
                "There's a request-logging middleware added in the same PR that reads request.Body to log the payload size, and it doesn't rewind. Since the body is a forward-only stream, by the time the decoder reads it it's at the end — zero bytes — so protobuf gets an empty batch. The gzip branch was a red herring; the real bug is the body being consumed upstream."),
            new("Ugh. Of course. So the logging middleware is the culprit, not the decode switch?",
                "Both landed in #204, but yes — the streaming decode only breaks because something now consumes the body first. Two fixes: enable buffering so the body can be re-read (EnableBuffering + rewind), or make the logger not read the body and use Content-Length for size. The second is cheaper and avoids double-reading megabytes."),
            new("Wrong again — I told you the size log is useful, I don't want to lose it. Just make it re-readable.",
                "Understood, keeping the size log. I'll call request.EnableBuffering() early in the pipeline so the body is backed by a re-readable buffer, and have the logging middleware seek back to 0 after reading. Then the decoder sees the full body.",
                Tools: ["editFile"]),
            new("Do it, and this time write the failing test first so we know it actually reproduces.",
                "Added Decoder_ReadsBody_AfterUpstreamMiddlewareConsumesIt — it runs the real middleware pipeline against a gzipped captured batch and asserts a non-zero decoded span count. Confirmed it FAILS on current code (decodes 0 spans). Now I have a red test that reproduces the incident.",
                Tools: ["createFile", "runTests"]),
            new("Good, red test. Now apply the EnableBuffering fix and make it green.",
                "Applied EnableBuffering and the rewind. Re-ran: the test now decodes all 340 spans from the captured batch — green. The decoder suite is 18 passed too.",
                Tools: ["editFile", "runTests"]),
            new("Replay the full captured prod traffic on staging.",
                "Replaying 14:00–14:10 against staging... decoded 100% of batches, zero empty results, ingest rate matches the pre-deploy baseline. The fix holds on real traffic.",
                Tools: ["runCommand"], ChatError: true, ErrorType: "RateLimitError", TtftMs: 3900),
            new("Now I'm nervous about the gzip branch you added earlier — still needed, or was it noise?",
                "Still needed, just not the incident cause. Before #204 the buffered path decompressed via a different code path the streaming rewrite dropped. With the body now re-readable, the decoder still has to gunzip gzipped bodies. So keep both the gzip branch AND the buffering fix — they're independent and both required."),
            new("Prove it — add a test for the gzip path specifically.",
                "Added Decoder_Decodes_GzipEncodedBody: sends a gzipped batch with Content-Encoding: gzip and asserts the span count matches the uncompressed control. It fails if I remove the gzip branch, passes with it. Both regression tests now guard the two independent failure modes.",
                Model: "claude-sonnet-5", Tools: ["editFile", "runTests"]),
            new("What about a plain uncompressed body — still works?",
                "Yes — added Decoder_Decodes_IdentityEncoding for the no-encoding case; the gzip branch is skipped and the raw body decodes. Passing. So identity, gzip, and consumed-then-rewound bodies are all covered.",
                Tools: ["editFile", "runTests"]),
            new("Before we redeploy the fixed build, I want a guardrail so a silent empty-decode never bleeds for 40 minutes again.",
                "Agreed — the silence was the scary part. I'll add otlp_decode_empty_total, incremented whenever a request decodes to zero spans despite a non-zero Content-Length, plus a warning log. An alert on that would have paged us in minutes instead of a customer noticing.",
                Tools: ["editFile"]),
            new("Add the alert threshold too, or at least document it.",
                "Documented in docs/RUNBOOK.md: alert when otlp_decode_empty_total exceeds 1% of otlp_requests_total over 5 minutes, with the two root causes we found (body consumed upstream, missing decompression) as the first things to check.",
                Tools: ["editFile"]),
            new("Why didn't CI catch this?",
                "Because every decoder test fed the decoder a body directly, bypassing the middleware pipeline. The bug only appears when a real pipeline consumes the body first, which no test exercised. The new AfterUpstreamMiddlewareConsumesIt test closes that gap, and I'd add an HTTP smoke test that posts a gzipped batch over the real stack."),
            new("Add the HTTP smoke test.",
                "Added IngestSmokeTests using WebApplicationFactory: it POSTs a gzipped OTLP batch to /v1/traces over the real pipeline and asserts 200 plus a non-zero stored span count. This is the end-to-end guard — it would have failed on the bad deploy.",
                Tools: ["createFile", "runTests"]),
            new("Run everything.",
                "Full suite: 214 passed, 0 failed. The four incident-regression tests and the smoke test are all green.",
                Model: "claude-opus-4-8", Tools: ["runTests"]),
            new("Let me read the final decoder + middleware diff before we ship.",
                "Here's the combined diff: EnableBuffering() in the pipeline setup, the logging middleware's seek-back-to-0, the gzip branch in DecodeAsync, and the empty-decode metric. Net ~40 lines. The streaming decode from #204 stays — it's fine now that the body is re-readable.",
                Tools: ["gitDiff"]),
            new("The EnableBuffering — does that buffer huge bodies to disk? Some batches are big.",
                "By default it spools to memory up to 30 KB then to a temp file. For large batches that's disk I/O per request on the hot path, which we don't want. I'll raise the memory threshold; question is how high without blowing up memory under concurrency.",
                Tools: ["editFile"]),
            new("What's our max concurrency? 1MB each could add up.",
                "At peak ~400 concurrent ingest requests. 1 MB each worst-case is ~400 MB of buffer — too much. I'll set it to 256 KB, which covers the p99 batch size we measured (180 KB) and caps worst-case buffer near 100 MB. Bigger batches spill to disk, which is rare and acceptable.",
                Tools: ["editFile"]),
            new("256KB, good. Re-run the smoke test with a 200KB batch to confirm it stays in memory.",
                "Added a 200 KB variant and asserted no temp-file spill via the request's buffering state. Passes — stays in memory, decodes fully.",
                Tools: ["editFile", "runTests"]),
            new("Ship the fixed build to staging, soak 15 minutes, then prod.",
                "Deployed to staging. Watching otlp_decode_empty_total and ingest rate for 15 minutes before promoting. So far: empty-decode flat at 0, ingest matching baseline.",
                Tools: ["runCommand"]),
            new("15 min clean. Promote to prod.",
                "Promoting the fixed build... deploy complete. Ingest is steady at baseline, otlp_decode_empty_total is 0, no 200-but-empty responses. The drop is resolved.",
                Tools: ["runCommand"], TtftMs: 3300),
            new("Confirmed on my end, dashboards are green. Write up the incident timeline.",
                "Drafted docs/incidents/2026-07-otlp-drop.md: 14:00 deploy of #204, 14:06 first drop, 14:20 detected, 14:35 rollback + recovery, root cause (logging middleware consumed the body before streaming decode; a latent missing-gzip branch compounded it), fix (EnableBuffering + rewind + gzip branch + empty-decode alert), and the CI gap that let it through.",
                Tools: ["createFile"]),
            new("Add an action item to audit other middleware for body consumption.",
                "Added: audit all middleware for un-rewound request.Body reads, and add a pipeline-level test that fails if any handler leaves the body consumed before the terminal decoder. Filed as a follow-up ticket reference.",
                Tools: ["editFile"]),
            new("Thanks for staying calm while I wasn't.",
                "No problem — incidents are stressful and the rollback bought us time to do it right. The silent-drop guardrail is the real win; next time this class of bug pages us in minutes. Everything's committed on the hotfix branch; if the overnight soak stays clean you can merge into develop tomorrow."),
        ]);

    // ── Session 3 ─────────────────────────────────────────────────────────────────────────────
    // A frontend dev builds a search page with debounced query + infinite scroll in React/TS,
    // hook-first: race-safe fetching, IntersectionObserver pagination, a11y, loading/empty/error
    // states, tests, and a nice AbortError catch at the end. VS Code, with a mid-session model
    // switch during the virtualization discussion.
    private static ScriptedSession InfiniteScrollSearch => new(
        Slug: "search-infinite-scroll",
        Repository: "https://github.com/acme/frontend-shell",
        Branch: "feature/search-v2",
        Emitter: EmitterKind.VSCode,
        DefaultModel: "claude-sonnet-5",
        EditsAccepted: 38, EditsRejected: 4, ThumbsUp: 5, ThumbsDown: 0,
        LinesAdded: 524, LinesRemoved: 92,
        Turns:
        [
            new("I'm building a search page in frontend-shell — text search with infinite scroll, React + TypeScript. Where should I start?",
                "Data contract and the hook first, UI last. Define the search API shape (query + cursor in, results + nextCursor out), then a useInfiniteSearch hook that owns query state, debouncing, pagination and loading flags. The component becomes a thin renderer over the hook. Want me to scaffold the hook first?"),
            new("Yes, scaffold the hook.",
                "Added src/hooks/useInfiniteSearch.ts. It holds query, results, nextCursor, isLoading and error, and exposes setQuery and loadMore. loadMore and the query effect are stubbed for now — I'll fill in fetching next. Typed the result as generic <T> so it isn't search-page-specific.",
                Tools: ["createFile"]),
            new("Add debouncing on the query so we don't fire a request per keystroke.",
                "Added a 300 ms debounce: setQuery updates the input immediately (so the field stays responsive) but the fetch effect keys off a debounced value. I used a small useDebouncedValue hook rather than lodash to keep the bundle lean.",
                Tools: ["createFile", "editFile"]),
            new("Why a separate debounced value instead of debouncing the fetch itself?",
                "Because the input must update on every keystroke to feel responsive — if you debounce the state backing the input, typing feels laggy. Debouncing a derived value lets the visible input track keystrokes at full speed while only the fetch waits for the 300 ms pause. It also makes the debounce trivially testable in isolation."),
            new("Now wire the actual fetch — new query resets results, loadMore appends.",
                "Done. The query effect resets results and nextCursor and fetches page one; loadMore fetches with the stored cursor and appends. Both go through one fetchPage(query, cursor) helper so the request shape is defined once.",
                Tools: ["editFile"]),
            new("There's a race: if I type fast, an old query's response can land after the new one and clobber results. Handle that.",
                "Classic out-of-order response bug. I added an AbortController per query effect — when the query changes the previous request is aborted — plus a request-id ref so a stale response that still resolves is ignored. Only the latest query can write results.",
                Tools: ["editFile"]),
            new("Show me how loadMore avoids double-firing when the user scrolls fast.",
                "loadMore early-returns if isLoading is already true or nextCursor is null, so overlapping scroll events collapse into one in-flight request. The next call is only allowed after the current page resolves and the cursor advances.",
                Tools: ["readFile"]),
            new("Now the component. Use an IntersectionObserver sentinel for the infinite scroll, not a scroll listener.",
                "Added SearchResults.tsx with a sentinel div at the list's end and an IntersectionObserver that calls loadMore when it enters the viewport. Observer-based beats scroll math — no manual offset calculations, and it naturally handles variable-height rows.",
                Tools: ["createFile"]),
            new("Loading and empty states?",
                "Three states: a skeleton list on the initial load, a small inline spinner by the sentinel while paging, and an empty state (No results for …) when a completed search returns nothing. The empty state only shows after a fetch settles, so it doesn't flash during typing.",
                Tools: ["editFile"]),
            new("Error state too — the API can 500.",
                "Added an error banner with a Retry button that re-runs the last query. For a mid-pagination error I keep the already-loaded results and show the error only at the bottom, so a failed page 3 doesn't wipe pages 1–2.",
                Tools: ["editFile"]),
            new("Keyboard accessibility — I want arrow keys to move through results.",
                "Added roving-tabindex: the list is role=listbox, each result role=option, ArrowUp/Down move focus and set aria-activedescendant, Enter activates. Focus follows into newly loaded pages so keyboard users can page in without touching the mouse.",
                Tools: ["editFile"]),
            new("Does the IntersectionObserver still fire for keyboard users who never scroll with the mouse?",
                "It fires on any reason the sentinel becomes visible, including focus scrolling the list. But to be safe I also trigger loadMore when focus reaches the last loaded option, so keyboard-only navigation never dead-ends before the observer catches up.",
                Tools: ["editFile"]),
            new("Now tests. Start with the hook's debounce + race handling.",
                "Added useInfiniteSearch.test.tsx with React Testing Library + fake timers. Cases: rapid setQuery fires one fetch after 300 ms; an out-of-order slow response for an old query is ignored; loadMore appends and advances the cursor. All green.",
                Tools: ["createFile", "runTests"]),
            new("Add a test that loadMore doesn't double-fire.",
                "Added loadMore_isNoOp_whileLoading: calls loadMore twice back-to-back with a pending fetch and asserts only one request goes out. Passing.",
                Tools: ["editFile", "runTests"]),
            new("Component tests — empty and error states.",
                "Added SearchResults.test.tsx: renders the empty state after a zero-result search, renders the error banner on a rejected fetch and recovers on Retry, and keeps prior results when a later page errors. Green.",
                Tools: ["createFile", "runTests"]),
            new("The IntersectionObserver — how are you testing that without a real viewport?",
                "Mocked IntersectionObserver with a tiny fake that lets the test manually intersect the sentinel, then asserted loadMore was called. Standard approach — we test the observer wiring, not the browser's intersection math.",
                Tools: ["editFile"]),
            new("I noticed results flicker when a new search starts — old results flash before the skeleton. Fix.",
                "That's because I reset results in an effect after paint. I moved the reset to happen synchronously when the debounced query changes, before the fetch, so the list clears to the skeleton immediately instead of showing stale rows for a frame.",
                Tools: ["editFile"]),
            new("Better. But a fast backspace-to-empty shows the skeleton then empty — should just clear.",
                "Added a guard: an empty or whitespace-only query short-circuits to a cleared, non-loading state and fires no request. So clearing the box returns to the initial prompt, not a skeleton-then-empty flash.",
                Tools: ["editFile"]),
            // Model switch for the perf side-discussion, plus a slower response while it 'thinks'.
            new("Performance — with 500+ results the DOM gets heavy. Do we need virtualization?",
                "At 500 rows you'll feel scroll jank, yes. I'd add @tanstack/react-virtual to render only the visible window; it composes with the IntersectionObserver if the sentinel is the last virtual item. Want me to add it, or defer until we confirm real result sets get that large?",
                Model: "gpt-4o", TtftMs: 2600),
            new("Defer it — most searches return under 100. Just leave a comment noting the threshold.",
                "Added a comment at the list render marking ~200 rows as the point to introduce virtualization, with the react-virtual approach noted so it's a quick change later. Not pulling the dependency in now.",
                Tools: ["editFile"]),
            new("Now hook it to the real endpoint. It's GET /api/search?q=&cursor=.",
                "Wired fetchPage to GET /api/search with q and cursor params, mapping the response items/nextCursor into the hook's shape. Kept the fetch in a searchApi.ts module so the hook stays transport-agnostic and mockable.",
                Model: "claude-sonnet-5", Tools: ["createFile", "editFile"]),
            new("The cursor is opaque base64 — make sure we URL-encode it.",
                "Yes — encodeURIComponent on the cursor before appending. Without it a + or = in the base64 would corrupt the query string. Added a test asserting a cursor with those chars round-trips correctly.",
                Tools: ["editFile", "runTests"]),
            new("Add a loading indicator in the search box itself — a spinner on the right while fetching.",
                "Added an inline spinner in the input's trailing slot, shown while a query fetch (not pagination) is in flight. It's aria-hidden with aria-busy on the input, so screen readers get the state without a spinning-icon announcement.",
                Tools: ["editFile"]),
            new("Mobile — does the infinite scroll work with touch momentum?",
                "IntersectionObserver is input-agnostic, so touch momentum triggers it the same as mouse. I bumped the sentinel's rootMargin to 200px so the next page starts loading before the user hits the very bottom — on mobile that hides the fetch latency behind the fling.",
                Tools: ["editFile"]),
            new("Test the responsive layout doesn't break the observer.",
                "The observer watches the sentinel regardless of layout, so responsive changes don't affect it. Added a test rendering at a narrow width asserting the grid collapses to one column and the sentinel still triggers loadMore. Green.",
                Tools: ["editFile", "runTests"]),
            new("Run the full frontend suite and lint.",
                "Ran both: 63 tests passed, 0 failed; eslint clean, no type errors from tsc --noEmit. The new files are covered at 94% lines.",
                Tools: ["runCommand", "runTests"]),
            new("Let me eyeball the hook one more time — paste useInfiniteSearch.",
                "Here's the final useInfiniteSearch.ts: debounced query, AbortController + request-id race guard, synchronous reset on query change, empty-query short-circuit, and the loadMore no-op guard. It's ~90 lines and transport-agnostic via the injected fetchPage.",
                Tools: ["readFile"]),
            new("The error type is any in the catch — narrow it.",
                "Narrowed it: I catch unknown, ignore AbortError (that's our own cancellation, not a real error), and otherwise store a normalized { message }. No more any, and aborts no longer surface as user-facing errors.",
                Tools: ["editFile"]),
            new("Great catch on the AbortError — that would've shown a fake error banner on every keystroke. Commit it.",
                "Staged. Suggested message: feat(frontend-shell): search with debounced query and infinite scroll — body covering the race-safe hook, IntersectionObserver pagination, a11y (listbox + roving tabindex), loading/empty/error states, and the deferred-virtualization note. Want the PR opened?",
                Tools: ["editFile"]),
            new("Open it against main. Good work.",
                "Opened PR #488 into main with the summary and test coverage (94%). CI's running. Thanks — this one came together cleanly; the hook-first approach kept the component simple.",
                Tools: ["runCommand"]),
        ]);
}
